/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AccountObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The current status of the account - `draft`, `pending` or `active`
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type AccountParameters struct {

	// Cloud provider access key
	// +kubebuilder:validation:Required
	AccessKeyID *string `json:"accessKeyId" tf:"access_key_id,omitempty"`

	// Cloud provider secret key
	// +kubebuilder:validation:Required
	AccessSecretKeySecretRef v1.SecretKeySelector `json:"accessSecretKeySecretRef" tf:"-"`

	// Cloud provider management console password
	// +kubebuilder:validation:Required
	ConsolePasswordSecretRef v1.SecretKeySelector `json:"consolePasswordSecretRef" tf:"-"`

	// Cloud provider management console username
	// +kubebuilder:validation:Required
	ConsoleUsername *string `json:"consoleUsername" tf:"console_username,omitempty"`

	// Display name of the account
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// Cloud provider type - either `AWS` or `GCP`
	// +kubebuilder:validation:Required
	ProviderType *string `json:"providerType" tf:"provider_type,omitempty"`

	// Cloud provider management console login URL
	// +kubebuilder:validation:Required
	SignInLoginURL *string `json:"signInLoginUrl" tf:"sign_in_login_url,omitempty"`
}

// AccountSpec defines the desired state of Account
type AccountSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AccountParameters `json:"forProvider"`
}

// AccountStatus defines the observed state of Account.
type AccountStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccountObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Account is the Schema for the Accounts API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rediscloud}
type Account struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AccountSpec   `json:"spec"`
	Status            AccountStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountList contains a list of Accounts
type AccountList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Account `json:"items"`
}

// Repository type metadata.
var (
	Account_Kind             = "Account"
	Account_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Account_Kind}.String()
	Account_KindAPIVersion   = Account_Kind + "." + CRDGroupVersion.String()
	Account_GroupVersionKind = CRDGroupVersion.WithKind(Account_Kind)
)

func init() {
	SchemeBuilder.Register(&Account{}, &AccountList{})
}
