apiVersion: database.rediscloud.upbound.io/v1alpha1
kind: Database
metadata:
  name: "crossplane-database"
spec:
  forProvider:
    subscriptionId: 1890183
    name: "crossplane-database"
    protocol: "redis"
    memoryLimitInGb: 1
    dataPersistence: "none"
    throughputMeasurementBy: "operations-per-second"
    throughputMeasurementValue: 1000
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: crossplane-database-password
    namespace: default